
version: '3.4'
x-logging: &default-logging
    driver: splunk
    options:
        splunk-token: 11111111-1111-1111-1111-1111111111113
        splunk-url: https://localhost:8088
        splunk-index: logs
        splunk-sourcetype: docker
        splunk-insecureskipverify: 'true'
        splunk-verify-connection: 'false'
        splunk-format: 'raw'
        tag: '{{.Name}}-{{.ID}}'

services:

  bootnode:
    build:
      context: besu/.
      args:
        BESU_VERSION: ${BESU_VERSION}
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    entrypoint: /opt/besu/bootnode_start.sh --network=dev --config-file=/config/config.toml --min-gas-price=0
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp

  minernode:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: [
      "--config-file=/config/config.toml",
      "--network=dev",
      "--miner-enabled=true",
      "--miner-coinbase=${MINER_COINBASE}"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
    depends_on:
      - bootnode

  node:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: [
      "--config-file=/config/config.toml",
      "--network=dev"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
    depends_on:
      - bootnode

  besurpc:
    image: sample-network/besu:${BESU_VERSION}
    container_name: besurpc
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - BESU_RPC_WS_ENABLED=true
      - BESU_HOST_WHITELIST=*
      - BESU_RPC_WS_HOST=0.0.0.0
      - BESU_RPC_HTTP_API=admin,eth,debug,miner,net,txpool,priv,trace,web3
      - BESU_LOGGING=trace
      # Splunk logging configuration
      - LOGGER=Splunk
      - SPLUNK_URL=https://splunk:8088
      - SPLUNK_INDEX=logs
      - SPLUNK_TOKEN=11111111-1111-1111-1111-1111111111113
      - SPLUNK_SKIPTLSVERIFY=true
    logging: *default-logging  
    command: [
      "--config-file=/config/config.toml",
      "--network=dev"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
    depends_on:
      - bootnode
    ports:
      - 8545:8545
#     networks:
#       - besu_splunk_ethereumconnector_default

# networks: 
#   besu_splunk_ethereumconnector_default:
#     external: true


  
volumes:
  public-keys:


