version: '3.6'

x-logging: &default-logging
    driver: splunk
    options:
        splunk-token: 11111111-1111-1111-1111-1111111111113
        splunk-url: https://localhost:8088
        splunk-index: logs
        splunk-sourcetype: docker
        splunk-insecureskipverify: 'true'
        splunk-verify-connection: 'false'
        splunk-format: 'raw'
        tag: '{{.Name}}-{{.ID}}'
volumes:
    splunk-besu:        

services:
    splunk:
        image: splunk/splunk:latest
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=changeme1
            - SPLUNK_APPS_URL=https://github.com/splunk/ethereum-basics/releases/download/latest/ethereum-basics.tgz

        ports:
            - 8000:8000
            - 8088:8088
            - 8089:8089
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000']
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - ./splunk.yml:/tmp/defaults/default.yml
            - /opt/splunk/var
            - /opt/splunk/etc
            - splunk-besu:/opt/splunk/etc/apps/search
        networks: 
            - besu_nodes_default

    ethlogger:
        image: splunkdlt/ethlogger:latest
        container_name: ethlogger
        environment:
            - COLLECT_PEER_INFO=true
            - COLLECT_PENDING_TX=true
            - ETH_RPC_URL=http://besurpc:8545
            - NETWORK_NAME=dev
            - START_AT_BLOCK=latest
            - SPLUNK_HEC_URL=https://splunk:8088
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_EVENTS_INDEX=main
            - SPLUNK_METRICS_INDEX=metrics
            - SPLUNK_INTERNAL_INDEX=metrics
            - SPLUNK_HEC_REJECT_INVALID_CERTS=false
            - ABI_DIR=/app/abis
            - DEBUG=ethlogger:platforms,ethlogger:eth
        volumes:
            - ./abis:/app/abis
            - ./:/app
        depends_on:
            - splunk
        networks: 
            - besu_nodes_default
        restart: unless-stopped
        logging: *default-logging    
    
networks:
  besu_nodes_default:
    external: true


